# Generated by Django 5.2.3 on 2025-06-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=10)),
                ('store_address', models.TextField()),
                ('business_name', models.CharField(max_length=150)),
                ('business_type', models.CharField(choices=[('bakery', 'Bakery'), ('restaurant', 'Restaurant'), ('convenience_store', 'Convenience Store')], max_length=20)),
                ('store_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('store_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'business_business',
            },
            bases=('account.user',),
        ),
    ]
