# Generated by Django 5.2.3 on 2025-06-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='store_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='business',
            name='store_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
