# Generated by Django 5.1.4 on 2025-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='store_latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='business',
            name='store_longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
